[project]
name = "veritas"
version = "0.1.0"
description = "MCP study"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "mcp>=1.13.0",
    "sqlmodel>=0.0.24",
]
